language: go
sudo: false
go:
  - 1.4
  - 1.5
  - 1.6
  - tip

script:
  - go get gopkg.in/yaml.v2
  - go get github.com/stretchr/testify/assert
  - go get golang.org/x/crypto/openpgp
  - go get golang.org/x/crypto/openpgp/armor
  - go get golang.org/x/crypto/ssh/terminal
  - go vet ./...
  - go test ./...